version: "3.7"

services:
  app-rentx:
      build: .
      container_name: rentx_ignite
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app-rentx
      links:
        - database
        - redis-database
      depends_on:
        - database
        - redis-database

  database:
      image: postgres
      container_name: ignite
      restart: always
      ports:
        - 5434:5432
      environment:
        - POSTGRES_USER=rentex
        - POSTGRES_PASSWORD=jYVfzduBdjjF
        - POSTGRES_DB=rentx_ignite
      volumes:
        - pgdata:/data/postgres
  redis-database:
      image: redis:alpine
      container_name: ignite-reds
      restart: always
      ports:
        - 6379:6379
      volumes:
        - pgdata:/data/redis

volumes:
  pgdata:
    driver: local