version: "3.7"

services:
  app-rentx:
      build: .
      container_name: rentx_ignite
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app-rentx
      links:
        - database
      depends_on:
        - database

  database-rentx:
      image: postgres
      container_name: ignite
      restart: always
      ports:
        - 5434:5432
      environment:
        - POSTGRES_USER=rentex
        - POSTGRES_PASSWORD=jYVfzduBdjjF
        - POSTGRES_DB=rentx_ignite
      volumes:
        - pgdata:/data/postgres
  
volumes:
  pgdata:
    driver: local