version: "3.7"

services:
  database:
    image: postgres
    container_name: ignite
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx_ignite
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx_ignite
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local